### PR TITLE
PHP 8.1 support

### PR DESCRIPTION
**Pull request by vincentreitz**
Hello,

I've added PHP 8.1 support for one of my projects. Duno if you're interested in supporting it

It does pass almost all tests (more than in PHP 7 master). I'm a bit stuck with the last ones.

It currently links my own submodules as I PR them earlier, I will rebase this PR if you are willing to accept others :)

[Here](https://app.travis-ci.com/github/vincentreitz/cakephp-1.3.21/builds/240405684) is my travis build

### CODE REVIEW

**Comment by vincentreitz** [comment]
I'm so sorry, i was too confident as i passed all the tests through the web interface.

To be forgiven, i've done another PR that fixes all the failing tests (see #23)

**Comment by drpark** [comment]
i'm trying to migrate on php 8.1 our cms which works now perfectly on php 7.4, what a relief!
on php 8 the 2 most fails i see is on array_merge functions when some arguments are null. And the other one is on html email that is now sent in plain text?
if someone can point me out.

I did some extra debug for php 7.4 in complex cases like in plugin with prefixes when routes were not working perfectly for redirections. i will try to push a commit with all my enhancements soon. i would have like to make it work on 8.1 before doing that.

thanks for your help

**Comment by littleant** [comment]
Congratulations on porting everything over to PHP 7.4!
PHP 8.0 is the last PHP version that the unit-tests are running against, so there are no guarantees for PHP 8.1 other than @vincentreitz confidence in his port. The reason is/was that Travis didn't support PHP 8.1 back then.

I no longer work with CakePHP 1.3, so I have no experience how well PHP 8.1 is supported right now. But your enhancements are welcome as long as the unit-tests are still running through.

**Comment by vincentreitz** [comment]
What I can tell is we still use cake 1.3 with 8.1 for our own (big) app and it's working well, we use html email and it seems we were able to upgrade from php 7.4 without any big issue.

Of course some code might be not covered by unit tests, or by our own app. As the code is very old, I'm not that confident every use case still works. 

I could give a look at your issues @drpark if you cannot find out by yourself if can clarify them. I'm no expert of cake, I just dig into the framework and backported upstream our own fixes

**Comment by littleant** [comment]
I just enabled unit-tests for PHP 8.1 and fixed two tests that failed due to a PHP bug fix.
There are no PHP 8.1 specific problems in the unit-tests.

**Comment by drpark** [comment]
thank you all for your answer, we are finalizing the upgrade to 7.4 on all our apps, then i will come back to tests on php 8.1 knowing everithing is fine will be ok. 

What i saw most in my tests are array_merge failing cause of null params and html email beeing sent plain.
will dig deeper

**Comment by jonmbennett** [comment]
Has anyone tried it with PHP 8.2 yet? My app _seems_ to work fine with 8.2 at first glance, but I haven't tested it thoroughly or checked to see if any Cake framework tests fail.

**Comment by vincentreitz** [comment]
You may have some issue with dynamic properties as they are deprecated and cake 1.3 heavily based on them

https://wiki.php.net/rfc/deprecate_dynamic_properties

**Pull request merged**
